{{- if and (eq .Values.category "land") .Values.land.rentcastExternalSecret.enabled (not .Values.land.rentcastSecret) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-rentcast" (include "nagus.fullname" .) }}
  labels:
    {{- include "nagus.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.land.rentcastExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.land.rentcastExternalSecret.secretStoreRef.name }}
    kind: {{ .Values.land.rentcastExternalSecret.secretStoreRef.kind }}
  target:
    name: {{ printf "%s-rentcast" (include "nagus.fullname" .) }}
    creationPolicy: Owner
  data:
    - secretKey: NAGUS_RENTCAST_KEY
      remoteRef:
        key: {{ .Values.land.rentcastExternalSecret.remoteRef.key | quote }}
        property: {{ .Values.land.rentcastExternalSecret.remoteRef.property | quote }}
{{- end }}
