{{- if and (or (eq .Values.category "land") .Values.sources) .Values.land.zillapiExternalSecret.enabled (not .Values.land.zillapiSecret) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-zillapi" (include "nagus.fullname" .) }}
  labels:
    {{- include "nagus.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.land.zillapiExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.land.zillapiExternalSecret.secretStoreRef.name }}
    kind: {{ .Values.land.zillapiExternalSecret.secretStoreRef.kind }}
  target:
    name: {{ printf "%s-zillapi" (include "nagus.fullname" .) }}
    creationPolicy: Owner
  data:
    - secretKey: NAGUS_ZILLAPI_KEY
      remoteRef:
        key: {{ .Values.land.zillapiExternalSecret.remoteRef.key | quote }}
        property: {{ .Values.land.zillapiExternalSecret.remoteRef.property | quote }}
{{- end }}
