{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default (printf "%s-ebay" (include "nagus.fullname" .)) .Values.externalSecret.targetName }}
  labels:
    {{- include "nagus.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ default (printf "%s-ebay" (include "nagus.fullname" .)) .Values.externalSecret.targetName }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
{{- end }}
