{{- if and (eq .Values.storage.backend "sqlite") .Values.storage.sqlite.persistence.enabled (not .Values.storage.sqlite.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nagus.fullname" . }}-data
  labels:
    {{- include "nagus.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.sqlite.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.sqlite.persistence.size | quote }}
  {{- with .Values.storage.sqlite.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
