// Code generated by tools/genappellations; DO NOT EDIT.

// Appellation data derived from the LWIN database, (c) Liv-ex, licensed under
// the Creative Commons Attribution 4.0 licence
// (http://www.liv-ex.com/lwin-creative-commons-licence/).
//
// Changes from the source: only the REGION and SUB_REGION names of Live wines
// (TYPE "Wine" or "Fortified Wine") are used; names are accent-folded,
// lower-cased and punctuation-normalized; names with fewer than 20 wines,
// and the ordinary words, political places and names other rules handle, are
// dropped; the rest are tiered into appellations and broad regions. The
// generator's exclude and broad lists document every hand decision.

package wine

// lwinAppellations maps a normalized name to its tier: true for a broad
// region (evidence only beside a supporting cue), false for an appellation
// (evidence on its own).
var lwinAppellations = map[string]bool{
	"abruzzo":                              true,  // 542
	"aconcagua":                            true,  // 558
	"aconcagua valley":                     true,  // 46
	"acores":                               true,  // 28
	"adelaida district":                    true,  // 156
	"adelaide hills":                       true,  // 743
	"aegean islands":                       true,  // 146
	"aglianico del vulture":                false, // 88
	"ahr":                                  false, // 149
	"alentejano":                           true,  // 397
	"alentejo":                             true,  // 285
	"alexander valley":                     true,  // 346
	"algarve":                              true,  // 71
	"alicante":                             true,  // 96
	"almansa":                              false, // 37
	"aloxe corton":                         false, // 280
	"alpilles":                             false, // 40
	"alsace":                               true,  // 5510
	"alta langa":                           false, // 53
	"altenberg de bergheim":                false, // 26
	"alto adige":                           false, // 907
	"alto cachapoal":                       true,  // 21
	"amador county":                        true,  // 74
	"amarone della valpolicella":           false, // 375
	"ambonnay":                             false, // 59
	"ancient lakes of columbia valley":     true,  // 26
	"andalucia":                            true,  // 700
	"anderson valley":                      true,  // 372
	"anjou":                                false, // 193
	"applegate valley":                     true,  // 128
	"arbois":                               false, // 306
	"arbois pupillin":                      false, // 97
	"ardeche":                              true,  // 71
	"arribes":                              false, // 22
	"arroyo grande valley":                 true,  // 75
	"arroyo seco":                          true,  // 69
	"asolo prosecco":                       false, // 23
	"atlas peak":                           true,  // 54
	"auxey duresses":                       false, // 224
	"avize":                                false, // 66
	"awatere valley":                       true,  // 25
	"baden":                                true,  // 574
	"bairrada":                             false, // 175
	"ballard canyon":                       true,  // 133
	"bandol":                               false, // 129
	"banyuls":                              false, // 54
	"barbaresco":                           false, // 660
	"barbera d alba":                       false, // 441
	"barbera d asti":                       false, // 189
	"barbera del monferrato":               false, // 29
	"bardolino":                            false, // 88
	"barolo":                               false, // 1606
	"barolo chinato":                       false, // 24
	"barossa":                              true,  // 355
	"barossa valley":                       true,  // 1312
	"barsac":                               false, // 20
	"basilicata":                           true,  // 186
	"batard montrachet":                    false, // 137
	"beamsville bench":                     true,  // 100
	"beaujolais":                           false, // 1718
	"beaujolais villages":                  false, // 224
	"beaumes de venise":                    false, // 25
	"beaune":                               false, // 877
	"beechworth":                           true,  // 85
	"beira interior":                       true,  // 28
	"beiras":                               true,  // 24
	"bekaa valley":                         true,  // 105
	"bendigo":                              true,  // 46
	"beneventano":                          false, // 60
	"bennett valley":                       true,  // 52
	"bergerac":                             false, // 116
	"bienvenues batard montrachet":         false, // 39
	"bierzo":                               false, // 268
	"binissalem":                           false, // 20
	"bio bio valley":                       true,  // 53
	"blaye cotes de bordeaux":              false, // 234
	"bolgheri":                             false, // 188
	"bonnes mares":                         false, // 116
	"bonnezeaux":                           false, // 22
	"bordeaux":                             true,  // 7644
	"bordeaux superieur":                   false, // 523
	"bot river":                            true,  // 46
	"bourgogne":                            true,  // 2207
	"bourgogne aligote":                    false, // 437
	"bourgogne passe tout grains":          false, // 73
	"bourgueil":                            false, // 82
	"bouzeron":                             false, // 43
	"bouzy":                                false, // 46
	"breede river valley":                  true,  // 287
	"breedekloof":                          true,  // 54
	"breganze":                             false, // 29
	"brouilly":                             true,  // 137
	"brunello di montalcino":               false, // 634
	"bugey":                                false, // 25
	"burgenland":                           true,  // 1083
	"burgundy":                             true,  // 24357
	"cachapoal valley":                     true,  // 191
	"cadillac cotes de bordeaux":           false, // 64
	"cafayate":                             true,  // 104
	"cahors":                               false, // 149
	"cairanne":                             false, // 75
	"calabria":                             true,  // 138
	"calatayud":                            false, // 71
	"calaveras county":                     true,  // 26
	"calchaqui valley":                     true,  // 44
	"calistoga":                            true,  // 102
	"calitzdorp":                           true,  // 28
	"campania":                             true,  // 826
	"campi flegrei":                        false, // 28
	"campo de borja":                       false, // 83
	"canberra district":                    true,  // 50
	"cannonau di sardegna":                 false, // 108
	"canon fronsac":                        false, // 53
	"cape south coast":                     true,  // 676
	"carema":                               false, // 20
	"carignano del sulcis":                 false, // 21
	"carinena":                             false, // 181
	"carmel valley":                        true,  // 51
	"carnuntum":                            false, // 128
	"carso":                                false, // 28
	"casablanca valley":                    true,  // 288
	"castilla la mancha":                   true,  // 500
	"castilla y leon":                      true,  // 1777
	"castillon cotes de bordeaux":          false, // 197
	"catalunya":                            true,  // 1068
	"cauquenes":                            true,  // 21
	"cayuga lake":                          true,  // 21
	"central greece":                       true,  // 34
	"central otago":                        true,  // 568
	"cerasuolo d abruzzo":                  false, // 51
	"cerasuolo di vittoria":                false, // 26
	"cesanese del piglio":                  false, // 22
	"cevennes":                             true,  // 28
	"chablis":                              false, // 1385
	"chalk hill":                           true,  // 35
	"chalone":                              true,  // 55
	"chambertin":                           false, // 139
	"chambertin clos de beze":              false, // 97
	"chambolle musigny":                    false, // 803
	"chamoson":                             false, // 22
	"chapelle chambertin":                  false, // 40
	"charmes chambertin":                   false, // 204
	"chassagne montrachet":                 false, // 1126
	"chateau chalon":                       false, // 37
	"chateauneuf du pape":                  false, // 869
	"chehalem mountains":                   true,  // 242
	"chenas":                               false, // 69
	"chevalier montrachet":                 false, // 72
	"cheverny":                             false, // 34
	"chianti":                              false, // 239
	"chianti classico":                     false, // 667
	"chinon":                               false, // 187
	"chiroubles":                           false, // 61
	"chorey les beaune":                    false, // 99
	"chouilly":                             false, // 45
	"cienega valley":                       true,  // 26
	"cigales":                              false, // 40
	"ciro":                                 false, // 50
	"clare valley":                         true,  // 482
	"clarksburg":                           true,  // 65
	"clos de la roche":                     false, // 129
	"clos de vougeot":                      false, // 283
	"clos saint denis":                     false, // 58
	"colchagua valley":                     true,  // 547
	"colli della toscana centrale":         false, // 31
	"colli di luni":                        false, // 25
	"colli tortonesi":                      false, // 73
	"colline novaresi":                     false, // 41
	"colline pescaresi":                    false, // 30
	"collines rhodaniennes":                false, // 157
	"collio":                               false, // 215
	"collioure":                            false, // 59
	"columbia gorge":                       true,  // 142
	"columbia valley":                      true,  // 1836
	"conca de barbera":                     false, // 35
	"condado de huelva":                    false, // 23
	"condrieu":                             false, // 180
	"conegliano valdobbiadene superiore":   false, // 201
	"constantia":                           true,  // 90
	"contra costa county":                  true,  // 84
	"coombsville":                          true,  // 127
	"coonawarra":                           true,  // 266
	"coquimbo":                             true,  // 210
	"corbieres":                            false, // 165
	"cornas":                               false, // 162
	"corsica":                              true,  // 220
	"corton":                               false, // 573
	"corton charlemagne":                   false, // 262
	"cortona":                              true,  // 34
	"costa d amalfi":                       false, // 21
	"costa toscana":                        true,  // 56
	"costers del segre":                    false, // 70
	"costieres de nimes":                   false, // 139
	"cote de beaune":                       false, // 50
	"cote de beaune villages":              false, // 28
	"cote de brouilly":                     false, // 76
	"cote de nuits villages":               false, // 229
	"cote roannaise":                       false, // 23
	"cote rotie":                           false, // 337
	"coteaux bourguignons":                 false, // 143
	"coteaux champenois":                   false, // 138
	"coteaux d aix en provence":            false, // 107
	"coteaux de beziers":                   false, // 32
	"coteaux du layon":                     false, // 112
	"coteaux varois en provence":           false, // 51
	"cotes catalanes":                      false, // 241
	"cotes de bordeaux":                    false, // 41
	"cotes de bourg":                       false, // 202
	"cotes de gascogne":                    false, // 208
	"cotes de provence":                    false, // 655
	"cotes de thongue":                     false, // 65
	"cotes du jura":                        false, // 394
	"cotes du rhone":                       false, // 757
	"cotes du rhone villages":              false, // 270
	"cotes du roussillon":                  false, // 158
	"cotes du roussillon villages":         false, // 102
	"cowichan valley":                      true,  // 47
	"cramant":                              false, // 35
	"creek shores":                         true,  // 20
	"cremant d alsace":                     false, // 471
	"cremant de bordeaux":                  false, // 22
	"cremant de bourgogne":                 false, // 208
	"cremant de limoux":                    false, // 34
	"cremant de loire":                     false, // 72
	"cremant du jura":                      false, // 49
	"criots batard montrachet":             false, // 42
	"crozes hermitage":                     false, // 311
	"curico valley":                        true,  // 149
	"custoza":                              false, // 34
	"cyclades":                             true,  // 33
	"dalmacija":                            true,  // 47
	"dao":                                  false, // 297
	"delle venezie":                        false, // 212
	"diamond mountain district":            true,  // 80
	"dogliani":                             false, // 29
	"dolcetto d alba":                      false, // 209
	"douro":                                false, // 1014
	"dry creek valley":                     true,  // 267
	"dundee hills":                         true,  // 405
	"durbanville":                          true,  // 64
	"duriense":                             false, // 25
	"echezeaux":                            false, // 228
	"eden valley":                          true,  // 281
	"edna valley":                          true,  // 258
	"eichberg":                             false, // 52
	"eisenberg reserve":                    false, // 21
	"el dorado":                            true,  // 77
	"el dorado county":                     true,  // 40
	"el pomar district":                    true,  // 27
	"elim":                                 true,  // 20
	"elqui valley":                         true,  // 113
	"emilia":                               true,  // 84
	"emilia romagna":                       true,  // 351
	"emporda":                              false, // 46
	"ensenada":                             true,  // 20
	"entre deux mers":                      false, // 74
	"eola amity hills":                     true,  // 411
	"etna bianco":                          false, // 110
	"etna rosato":                          false, // 40
	"etna rosso":                           false, // 192
	"faugeres":                             false, // 61
	"fiano di avellino":                    false, // 83
	"finger lakes":                         true,  // 707
	"fitou":                                false, // 20
	"fixin":                                true,  // 159
	"fleurie":                              false, // 256
	"fleurieu":                             true,  // 33
	"fort ross seaview":                    true,  // 55
	"four mile creek":                      true,  // 37
	"franciacorta":                         false, // 268
	"francs cotes de bordeaux":             false, // 44
	"franken":                              true,  // 248
	"frankland river":                      true,  // 137
	"frankstein":                           false, // 42
	"franschhoek":                          true,  // 183
	"friuli colli orientali":               false, // 324
	"friuli grave":                         false, // 56
	"friuli isonzo":                        false, // 99
	"friuli venezia giulia":                true,  // 1053
	"fronsac":                              false, // 100
	"frusinate":                            false, // 26
	"furstentum":                           false, // 29
	"gaillac":                              false, // 41
	"galicia":                              true,  // 699
	"galilee":                              true,  // 126
	"gattinara":                            false, // 53
	"gavi":                                 false, // 147
	"geelong":                              true,  // 71
	"geographe":                            true,  // 32
	"getariako txakolina":                  false, // 45
	"gevrey chambertin":                    false, // 1167
	"gigondas":                             false, // 212
	"gimblett gravels":                     true,  // 107
	"gioia del colle":                      false, // 20
	"gippsland":                            true,  // 79
	"gisborne":                             true,  // 123
	"givry":                                false, // 173
	"golan heights":                        true,  // 28
	"golden mile bench":                    true,  // 26
	"goldert":                              false, // 43
	"goriska brda":                         false, // 206
	"goulburn valley":                      true,  // 30
	"grands echezeaux":                     false, // 69
	"graubunden":                           true,  // 168
	"graves":                               true,  // 409
	"graves de vayres":                     false, // 47
	"greco di tufo":                        false, // 79
	"green valley of russian river valley": true,  // 39
	"griotte chambertin":                   false, // 37
	"guerrouane":                           true,  // 24
	"happy canyon of santa barbara":        true,  // 116
	"haut medoc":                           false, // 366
	"hawke s bay":                          true,  // 788
	"heathcote":                            true,  // 166
	"hemel en aarde ridge":                 true,  // 21
	"hengst":                               false, // 46
	"hermitage":                            false, // 153
	"hessische bergstrasse":                false, // 32
	"horse heaven hills":                   true,  // 342
	"howell mountain":                      true,  // 208
	"hrvatska istra":                       true,  // 29
	"hunter valley":                        true,  // 368
	"ile de beaute":                        true,  // 50
	"irancy":                               false, // 46
	"irouleguy":                            false, // 32
	"irpinia":                              false, // 96
	"ischia":                               false, // 23
	"isola dei nuraghi":                    false, // 104
	"istria":                               true,  // 23
	"itata valley":                         true,  // 163
	"jerez":                                false, // 474
	"judean hills":                         true,  // 60
	"julienas":                             false, // 79
	"jumilla":                              false, // 155
	"jura":                                 true,  // 952
	"jurancon":                             false, // 86
	"kaefferkopf":                          false, // 51
	"kakheti":                              true,  // 106
	"kamptal":                              false, // 167
	"kamptal reserve":                      false, // 33
	"kangaroo island":                      true,  // 29
	"kirchberg de barr":                    false, // 21
	"klein karoo":                          true,  // 47
	"knights valley":                       true,  // 89
	"kremstal":                             false, // 146
	"kremstal reserve":                     false, // 53
	"kumeu":                                true,  // 28
	"l etoile":                             true,  // 25
	"la clape":                             false, // 32
	"la cote":                              true,  // 39
	"la mancha":                            true,  // 163
	"la rioja":                             true,  // 39
	"ladoix":                               false, // 133
	"lake chelan":                          true,  // 70
	"lake erie north shore":                true,  // 56
	"lalande de pomerol":                   false, // 197
	"lambrusco di sorbara":                 false, // 20
	"langhe":                               false, // 666
	"langhorne creek":                      true,  // 163
	"languedoc":                            true,  // 1813
	"lanzarote":                            true,  // 27
	"latricieres chambertin":               false, // 59
	"lavaux":                               false, // 28
	"lazio":                                true,  // 474
	"le mesnil sur oger":                   false, // 100
	"lehigh valley":                        true,  // 20
	"leithaberg":                           false, // 43
	"lenswood":                             true,  // 26
	"les baux de provence":                 false, // 32
	"leyda valley":                         true,  // 97
	"liguria":                              true,  // 97
	"limari valley":                        true,  // 94
	"limestone coast":                      true,  // 54
	"limoux":                               false, // 37
	"lincoln lakeshore":                    true,  // 56
	"lirac":                                false, // 80
	"lisboa":                               true,  // 271
	"listrac medoc":                        false, // 51
	"livermore valley":                     true,  // 47
	"lodi":                                 true,  // 309
	"loire":                                true,  // 3427
	"lombardia":                            true,  // 627
	"lontue valley":                        true,  // 27
	"los carneros":                         true,  // 515
	"los olivos district":                  true,  // 63
	"loupiac":                              false, // 22
	"luberon":                              false, // 67
	"lugana":                               false, // 94
	"lujan de cuyo":                        true,  // 277
	"lussac saint emilion":                 false, // 107
	"macedon ranges":                       true,  // 40
	"macon":                                false, // 371
	"macon villages":                       false, // 106
	"macvin du jura":                       false, // 25
	"madiran":                              false, // 52
	"maipo valley":                         true,  // 426
	"maipu":                                true,  // 58
	"malaga":                               true,  // 26
	"malgas":                               true,  // 25
	"mambourg":                             false, // 36
	"manchuela":                            false, // 36
	"manzanilla sanlucar de barrameda":     false, // 71
	"maranges":                             false, // 135
	"marche":                               true,  // 383
	"maremma toscana":                      false, // 149
	"mareuil sur ay":                       false, // 22
	"margaret river":                       true,  // 927
	"margaux":                              false, // 230
	"marlborough":                          true,  // 1434
	"marsannay":                            false, // 284
	"martinborough":                        true,  // 195
	"matakana":                             true,  // 56
	"maule valley":                         true,  // 413
	"maury":                                true,  // 74
	"mazis chambertin":                     false, // 112
	"mazoyeres chambertin":                 false, // 21
	"mclaren vale":                         true,  // 1230
	"mcminnville":                          true,  // 81
	"mediterranee":                         true,  // 121
	"medoc":                                false, // 360
	"mendocino":                            true,  // 83
	"mendocino county":                     true,  // 271
	"mendocino ridge":                      true,  // 53
	"mendoza":                              true,  // 3572
	"menetou salon":                        false, // 85
	"mentrida":                             false, // 30
	"mercurey":                             false, // 330
	"meursault":                            false, // 1434
	"middleburg virginia":                  true,  // 21
	"minervois":                            false, // 182
	"minho":                                true,  // 28
	"mittelburgenland":                     false, // 22
	"mittelrhein":                          false, // 22
	"mitterberg":                           false, // 24
	"mokelumne river":                      true,  // 20
	"molise":                               true,  // 50
	"monbazillac":                          false, // 46
	"monferrato":                           false, // 71
	"montagne saint emilion":               false, // 155
	"montagny":                             false, // 150
	"montefalco":                           false, // 47
	"montefalco sagrantino":                false, // 68
	"montepulciano d abruzzo":              false, // 228
	"monterey":                             true,  // 188
	"monterey county":                      true,  // 136
	"monterrei":                            false, // 33
	"monthelie":                            false, // 219
	"montilla moriles":                     false, // 65
	"montlouis sur loire":                  false, // 70
	"montrachet":                           false, // 84
	"montsant":                             false, // 174
	"moon mountain district":               true,  // 51
	"morellino di scansano":                false, // 74
	"morey saint denis":                    false, // 402
	"morgon":                               false, // 257
	"mornington peninsula":                 true,  // 228
	"moscato d asti":                       false, // 118
	"mosel":                                true,  // 3140
	"moselle luxembourgeoise":              true,  // 856
	"moulin a vent":                        false, // 200
	"moulis en medoc":                      false, // 65
	"mount barker":                         true,  // 69
	"mount veeder":                         true,  // 137
	"murray darling":                       true,  // 42
	"muscadet sevre et maine":              false, // 202
	"muscat de beaumes de venise":          false, // 31
	"muscat de rivesaltes":                 false, // 29
	"musigny":                              false, // 68
	"nahe":                                 false, // 577
	"naoussa":                              false, // 28
	"napa valley":                          true,  // 3773
	"naramata bench":                       true,  // 109
	"navarra":                              false, // 282
	"nebbiolo d alba":                      false, // 102
	"neuchatel":                            true,  // 38
	"neuquen":                              true,  // 20
	"neusiedlersee":                        false, // 37
	"niagara escarpment":                   true,  // 48
	"niagara lakeshore":                    true,  // 28
	"niagara on the lake":                  true,  // 106
	"niagara peninsula":                    true,  // 505
	"niagara river":                        true,  // 35
	"niederosterreich":                     true,  // 1875
	"nizza":                                true,  // 22
	"north canterbury":                     true,  // 67
	"north fork of long island":            true,  // 258
	"northern neck george washington birthplace": true, // 27
	"noto":                                   true,  // 27
	"nuits saint georges":                    false, // 1087
	"oak knoll district":                     true,  // 101
	"oakville":                               true,  // 321
	"obidos":                                 false, // 24
	"okanagan falls":                         true,  // 29
	"okanagan valley":                        true,  // 955
	"olifants river":                         true,  // 86
	"oltrepo pavese":                         false, // 46
	"oltrepo pavese metodo classico":         false, // 23
	"orvieto":                                false, // 51
	"overberg":                               true,  // 31
	"paarl":                                  true,  // 255
	"pacherenc du vic bilh":                  false, // 29
	"padthaway":                              true,  // 38
	"paestum":                                true,  // 37
	"pais vasco":                             true,  // 81
	"pantelleria":                            false, // 20
	"parras valley":                          true,  // 30
	"paso robles":                            true,  // 1697
	"paso robles highlands district":         true,  // 21
	"paso robles willow creek district":      true,  // 130
	"patrimonio":                             false, // 46
	"pauillac":                               false, // 162
	"pays d herault":                         false, // 168
	"pays d oc":                              false, // 882
	"pedernal":                               true,  // 23
	"peloponnese":                            true,  // 106
	"pemberton":                              true,  // 52
	"penedes":                                false, // 225
	"peninsula de setubal":                   true,  // 126
	"pernand vergelesses":                    false, // 260
	"pessac leognan":                         false, // 280
	"petaluma gap":                           true,  // 45
	"petit chablis":                          false, // 129
	"peumo":                                  true,  // 23
	"pfalz":                                  false, // 1322
	"pfersigberg":                            false, // 39
	"pic saint loup":                         false, // 41
	"piccadilly valley":                      true,  // 26
	"picpoul de pinet":                       false, // 60
	"piedmont":                               true,  // 5272
	"piekenierskloof":                        true,  // 62
	"piemonte":                               true,  // 54
	"pineau des charentes":                   false, // 26
	"pla i llevant":                          false, // 34
	"podravje":                               true,  // 52
	"pomerol":                                false, // 299
	"pommard":                                false, // 994
	"pouilly fuisse":                         false, // 469
	"pouilly fume":                           false, // 230
	"pouilly loche":                          false, // 20
	"pouilly vinzelles":                      false, // 24
	"premieres cotes de bordeaux":            false, // 59
	"primitivo di manduria":                  false, // 79
	"primorska":                              true,  // 283
	"prince edward county":                   true,  // 90
	"priorat":                                false, // 296
	"provence":                               true,  // 1125
	"provincia di pavia":                     false, // 38
	"puglia":                                 true,  // 947
	"puisseguin saint emilion":               false, // 70
	"puligny montrachet":                     false, // 909
	"quarts de chaume":                       false, // 22
	"quincy":                                 true,  // 30
	"rangen":                                 false, // 33
	"rapel valley":                           true,  // 110
	"rasteau":                                false, // 75
	"rattlesnake hills":                      true,  // 77
	"recioto della valpolicella":             false, // 78
	"recioto di soave":                       false, // 20
	"red mountain":                           true,  // 521
	"redwood valley":                         true,  // 23
	"regnie":                                 false, // 55
	"reuilly":                                false, // 38
	"rheingau":                               false, // 1064
	"rheinhessen":                            false, // 911
	"rhone":                                  true,  // 4904
	"rias baixas":                            false, // 352
	"ribbon ridge":                           true,  // 141
	"ribeira sacra":                          false, // 112
	"ribeiro":                                false, // 107
	"ribera del duero":                       false, // 744
	"ribera del guadiana":                    false, // 26
	"richebourg":                             false, // 68
	"rio negro":                              true,  // 68
	"rioja":                                  false, // 1467
	"riverina":                               true,  // 115
	"rivesaltes":                             false, // 76
	"riviera del garda classico":             false, // 24
	"riviera ligure di ponente":              false, // 41
	"rockpile":                               true,  // 31
	"roero":                                  false, // 202
	"rogue valley":                           true,  // 258
	"romagna":                                true,  // 63
	"romagna albana":                         false, // 20
	"romanee saint vivant":                   false, // 71
	"rosso conero":                           false, // 22
	"rosso di montalcino":                    false, // 199
	"rosso di montepulciano":                 false, // 24
	"rosso piceno":                           false, // 36
	"roussette de savoie":                    false, // 34
	"roussillon":                             true,  // 580
	"royal slope":                            true,  // 61
	"rubicone":                               false, // 49
	"ruchottes chambertin":                   false, // 24
	"rueda":                                  false, // 236
	"rully":                                  false, // 273
	"russian river valley":                   true,  // 1149
	"rutherford":                             true,  // 271
	"rutherglen":                             true,  // 108
	"saint amour":                            false, // 62
	"saint aubin":                            false, // 473
	"saint bris":                             false, // 27
	"saint chinian":                          false, // 94
	"saint david s bench":                    true,  // 27
	"saint emilion":                          false, // 411
	"saint emilion grand cru":                false, // 611
	"saint estephe":                          false, // 170
	"saint georges saint emilion":            false, // 28
	"saint guilhem le desert":                false, // 24
	"saint helena":                           true,  // 187
	"saint joseph":                           true,  // 396
	"saint julien":                           false, // 100
	"saint nicolas de bourgueil":             false, // 40
	"saint peray":                            false, // 65
	"saint romain":                           false, // 164
	"saint veran":                            false, // 197
	"sainte croix du mont":                   false, // 23
	"sainte foy bordeaux":                    false, // 32
	"salento":                                true,  // 312
	"salice salentino":                       false, // 46
	"salta":                                  true,  // 204
	"san antonio valley":                     true,  // 67
	"san juan":                               true,  // 141
	"san luis obispo county":                 true,  // 159
	"san rafael":                             true,  // 20
	"sancerre":                               false, // 755
	"sannio":                                 false, // 43
	"sant antimo":                            false, // 29
	"santa barbara county":                   true,  // 738
	"santa clara valley":                     true,  // 29
	"santa cruz mountains":                   true,  // 274
	"santa lucia highlands":                  true,  // 388
	"santa maria valley":                     true,  // 471
	"santa ynez valley":                      true,  // 554
	"santenay":                               false, // 504
	"santorini":                              false, // 93
	"sardinia":                               true,  // 462
	"saumur":                                 false, // 159
	"saumur champigny":                       false, // 130
	"sauternes":                              false, // 278
	"savennieres":                            false, // 76
	"savigny les beaune":                     false, // 604
	"savoie":                                 true,  // 320
	"schlossberg":                            false, // 47
	"schoenenbourg":                          false, // 44
	"seneca lake":                            true,  // 143
	"shenandoah valley":                      true,  // 114
	"sicilia":                                true,  // 408
	"sicily":                                 true,  // 1949
	"sierra foothills":                       true,  // 78
	"similkameen valley":                     true,  // 71
	"simonsberg paarl":                       true,  // 45
	"simonsberg stellenbosch":                true,  // 28
	"sjalland":                               true,  // 56
	"skaha bench":                            true,  // 20
	"slavonija":                              true,  // 23
	"snake river valley":                     true,  // 69
	"snipes mountain":                        true,  // 30
	"soave":                                  false, // 138
	"sommerberg":                             false, // 27
	"somontano":                              false, // 60
	"sonoita":                                true,  // 33
	"sonoma coast":                           true,  // 972
	"sonoma county":                          true,  // 602
	"sonoma mountain":                        true,  // 72
	"sonoma valley":                          true,  // 360
	"southern oregon":                        true,  // 45
	"spring mountain district":               true,  // 91
	"sta rita hills":                         true,  // 902
	"stags leap district":                    true,  // 126
	"stajerska slovenija":                    true,  // 42
	"stefan voda":                            true,  // 37
	"steiermark":                             true,  // 465
	"stellenbosch":                           true,  // 1509
	"strathbogie ranges":                     true,  // 31
	"sud ouest":                              true,  // 964
	"sudsteiermark":                          false, // 290
	"swartland":                              true,  // 462
	"taurasi":                                false, // 88
	"tavel":                                  false, // 38
	"tejo":                                   true,  // 101
	"templeton gap district":                 true,  // 60
	"tenerife":                               true,  // 41
	"terra alta":                             false, // 69
	"terrasses du larzac":                    false, // 71
	"terre del volturno":                     false, // 22
	"terre di chieti":                        false, // 61
	"terre siciliane":                        false, // 686
	"texas high plains":                      true,  // 236
	"texas hill country":                     true,  // 48
	"the rocks district of milton freewater": true,  // 24
	"thermenregion":                          false, // 112
	"thracian lowlands":                      true,  // 50
	"ticino":                                 true,  // 107
	"tierra de leon":                         false, // 21
	"tokaj":                                  false, // 292
	"toro":                                   true,  // 223
	"toscana":                                true,  // 911
	"touraine":                               false, // 237
	"tras os montes":                         true,  // 66
	"trebbiano d abruzzo":                    false, // 72
	"trentino":                               true,  // 119
	"trentino alto adige":                    true,  // 1166
	"trento":                                 true,  // 83
	"trevenezie":                             false, // 48
	"tulbagh":                                true,  // 48
	"tumbarumba":                             true,  // 56
	"tupungato":                              true,  // 256
	"tuscany":                                true,  // 4209
	"twenty mile bench":                      true,  // 68
	"uco valley":                             true,  // 898
	"umbria":                                 true,  // 442
	"umpqua valley":                          true,  // 33
	"upper galilee":                          true,  // 20
	"upper hemel en aarde valley":            true,  // 34
	"utiel requena":                          false, // 101
	"vacqueyras":                             false, // 170
	"val de loire":                           true,  // 159
	"valais":                                 true,  // 371
	"valdeorras":                             false, // 73
	"valdobbiadene superiore di cartizze":    false, // 24
	"valle d aosta":                          false, // 109
	"valle de guadalupe":                     true,  // 249
	"valpolicella":                           false, // 197
	"valpolicella ripasso":                   false, // 170
	"valtellina superiore":                   false, // 81
	"valul lui traian":                       true,  // 79
	"vancouver island":                       true,  // 43
	"vardar river valley":                    true,  // 21
	"vaucluse":                               true,  // 99
	"vaud":                                   true,  // 106
	"veneto":                                 true,  // 1790
	"venezia giulia":                         true,  // 229
	"ventoux":                                false, // 150
	"verdicchio dei castelli di jesi":        false, // 87
	"verdicchio di matelica":                 false, // 25
	"vermentino di gallura":                  false, // 44
	"vermentino di sardegna":                 false, // 67
	"vernaccia di san gimignano":             false, // 46
	"verzenay":                               false, // 35
	"verzy":                                  false, // 29
	"vesuvio":                                false, // 25
	"vigneti delle dolomiti":                 false, // 146
	"villany":                                false, // 20
	"vin de corse":                           false, // 68
	"vin de savoie":                          false, // 228
	"vin des allobroges":                     false, // 31
	"vin santo del chianti":                  false, // 29
	"vin santo del chianti classico":         false, // 27
	"vinemount ridge":                        true,  // 21
	"vinho verde":                            false, // 224
	"vino nobile di montepulciano":           false, // 100
	"vinos de madrid":                        false, // 71
	"vinsobres":                              false, // 24
	"vipavska dolina":                        false, // 44
	"vire clesse":                            false, // 94
	"volnay":                                 false, // 785
	"voor paarderberg":                       true,  // 25
	"vosne romanee":                          false, // 765
	"vougeot":                                false, // 53
	"vouvray":                                false, // 250
	"vulkanland steiermark":                  false, // 26
	"wachau":                                 false, // 487
	"wagram":                                 false, // 159
	"wahluke slope":                          true,  // 170
	"waiheke island":                         true,  // 146
	"waipara":                                true,  // 179
	"wairarapa":                              true,  // 287
	"walker bay":                             true,  // 160
	"walla walla valley":                     true,  // 812
	"weinland":                               true,  // 100
	"weinviertel":                            false, // 79
	"western cape":                           true,  // 780
	"weststeiermark":                         false, // 23
	"willamette valley":                      true,  // 1557
	"willcox":                                true,  // 145
	"wrattonbully":                           true,  // 39
	"wurttemberg":                            true,  // 196
	"yakima valley":                          true,  // 764
	"yamhill carlton":                        true,  // 288
	"yarra valley":                           true,  // 621
	"yecla":                                  false, // 69
	"yorkville highlands":                    true,  // 31
	"yountville":                             true,  // 83
	"zinnkoepfle":                            false, // 49
	"zotzenberg":                             false, // 22
}
